#!/usr/bin/env bash
# Eidolon dev toolkit - ALIENTEK ATK-DNESP32S3
#
# Usage:
#   ./scripts/eidolon/eidolon-atk-dnesp32s3.sh build
#   ./scripts/eidolon/eidolon-atk-dnesp32s3.sh flash
#   ./scripts/eidolon/eidolon-atk-dnesp32s3.sh monitor
#
# Environment:
#   EIDOLON_PORT        Serial port, for example /dev/cu.usbmodem1101
#   EIDOLON_IDF_EXPORT Full path to ESP-IDF export.sh
#   EIDOLON_IDF_PATH   ESP-IDF root directory
#   IDF_PATH           ESP-IDF root directory

set -euo pipefail

readonly BOARD_PATH="atk-dnesp32s3"
readonly BOARD_NAME="atk-dnesp32s3"
readonly BOARD_TARGET="esp32s3"
readonly BUILD_DIR="build/eidolon/atk-dnesp32s3"
readonly SDKCONFIG_FILE="${BUILD_DIR}/sdkconfig.atk-dnesp32s3"
readonly SDKCONFIG_OVERLAY="${BUILD_DIR}/sdkconfig.overlay.atk-dnesp32s3"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PORT="${EIDOLON_PORT:-}"

# Shared helper: SDK version pin + forced re-resolution, build fingerprint,
# post-flash serial verification. See scripts/eidolon/eidolon-common.sh.
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/eidolon-common.sh"

die() {
  echo "error: $*" >&2
  exit 1
}

info() {
  echo ">> $*"
}

idf_ready() {
  command -v idf.py >/dev/null 2>&1
}

idf_tools_ready() {
  idf_ready && command -v ninja >/dev/null 2>&1 && [[ -n "${IDF_PYTHON_ENV_PATH:-}" ]]
}

idf_export_candidates() {
  [[ -n "${EIDOLON_IDF_EXPORT:-}" ]] && echo "${EIDOLON_IDF_EXPORT}"

  local cfg="${SCRIPT_DIR}/idf.path"
  if [[ -f "${cfg}" ]]; then
    local line
    while IFS= read -r line || [[ -n "${line}" ]]; do
      line="${line%%#*}"
      line="${line#"${line%%[![:space:]]*}"}"
      line="${line%"${line##*[![:space:]]}"}"
      [[ -n "${line}" ]] && echo "${line%/}/export.sh"
    done <"${cfg}"
  fi

  [[ -n "${EIDOLON_IDF_PATH:-}" ]] && echo "${EIDOLON_IDF_PATH%/}/export.sh"
  [[ -n "${IDF_PATH:-}" ]] && echo "${IDF_PATH%/}/export.sh"

  local home="${HOME:-}"
  if [[ -n "${home}" ]]; then
    shopt -s nullglob
    local d
    for d in "${home}"/.espressif/v*/esp-idf/export.sh; do
      echo "${d}"
    done | sort -t'/' -k6 -V -r
    shopt -u nullglob
    echo "${home}/esp/esp-idf/export.sh"
    echo "${home}/esp-idf/export.sh"
  fi
}

ensure_idf_env() {
  if idf_tools_ready; then
    return 0
  fi

  local export_sh
  while IFS= read -r export_sh; do
    [[ -f "${export_sh}" ]] || continue
    info "Loading ESP-IDF: ${export_sh}"
    # shellcheck source=/dev/null
    source "${export_sh}"
    idf_tools_ready && return 0
  done < <(idf_export_candidates | awk '!seen[$0]++')

  return 1
}

require_idf() {
  ensure_idf_env || die "ESP-IDF tools not ready. Set EIDOLON_IDF_PATH or source export.sh first."
}

list_ports() {
  local -a patterns=(
    /dev/cu.usbmodem*
    /dev/cu.wchusbserial*
    /dev/cu.SLAB_USBtoUART*
    /dev/cu.usbserial*
    /dev/ttyUSB*
    /dev/ttyACM*
  )
  local p
  for p in "${patterns[@]}"; do
    [[ -e "${p}" ]] && echo "${p}"
  done
  return 0
}

detect_port() {
  if [[ -n "${PORT}" ]]; then
    echo "${PORT}"
    return 0
  fi

  local -a ports=()
  while IFS= read -r line; do
    [[ -n "${line}" ]] && ports+=("${line}")
  done < <(list_ports | sort -u)

  if ((${#ports[@]} == 0)); then
    die "No USB serial port found. Set EIDOLON_PORT=/dev/cu.xxx"
  fi
  if ((${#ports[@]} > 1)); then
    printf 'Multiple serial ports found; set EIDOLON_PORT explicitly:\n' >&2
    printf '  %s\n' "${ports[@]}" >&2
    exit 1
  fi
  echo "${ports[0]}"
}

write_overlay() {
  mkdir -p "${PROJECT_ROOT}/${BUILD_DIR}"
  cat >"${PROJECT_ROOT}/${SDKCONFIG_OVERLAY}" <<EOF
# Generated by scripts/eidolon/eidolon-atk-dnesp32s3.sh
CONFIG_BOARD_TYPE_ATK_DNESP32S3=y
CONFIG_EIDOLON_HUB_MODE=y
CONFIG_EIDOLON_AUTO_JOIN_ON_ACTIVATION=n
CONFIG_EIDOLON_DEV_DISABLE_AUTO_SHUTDOWN=y
# CONFIG_EIDOLON_INTERACTION_MODE_PTT is not set
CONFIG_EIDOLON_INTERACTION_MODE_HALF_DUPLEX=y
CONFIG_EIDOLON_LIVEKIT_SPEAKER_VOLUME=50
CONFIG_EIDOLON_OWNER_FACE_PROFILE=y
CONFIG_EIDOLON_OWNER_PERSON_PRESENCE=y
CONFIG_EIDOLON_AMBIENT_PRESENCE_OWNER_AUTH=y
# Prefer PSRAM for medium-sized C++ orchestration objects and queue storage.
# LiveKit/FreeRTOS/DMA allocations that explicitly require internal memory keep
# using the reserved internal pool.
CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=256
CONFIG_HUMAN_FACE_DETECT_MODEL_IN_FLASH_PARTITION=y
# CONFIG_HUMAN_FACE_DETECT_MODEL_IN_FLASH_RODATA is not set
CONFIG_HUMAN_FACE_FEAT_MODEL_IN_FLASH_PARTITION=y
# CONFIG_HUMAN_FACE_FEAT_MODEL_IN_FLASH_RODATA is not set
# CONFIG_EIDOLON_WAKE_WORD_ENABLE is not set
CONFIG_WAKE_WORD_DISABLED=y
# CONFIG_USE_ESP_WAKE_WORD is not set
# CONFIG_USE_AFE_WAKE_WORD is not set
# CONFIG_USE_CUSTOM_WAKE_WORD is not set
# CONFIG_SEND_WAKE_WORD_DATA is not set
# CONFIG_SR_WN_WN9_NIHAOXIAOZHI_TTS is not set
# CONFIG_CAMERA_OV2640 is not set
CONFIG_CAMERA_OV5640=y
CONFIG_CAMERA_OV5640_AUTO_DETECT_DVP_INTERFACE_SENSOR=y
CONFIG_CAMERA_OV5640_DVP_YUV422_800X600_10FPS=y
CONFIG_CAMERA_OV5640_DVP_IF_FORMAT_INDEX_DEFAULT=0
# Shrink esp32-camera's internal DMA line buffer (default 32768) to the minimum
# so the freed internal DMA lets LiveKit 0.3.10's capture sink allocate and the
# guard joins its control room. QVGA RGB565 capture is fine at 8192.
CONFIG_CAMERA_DMA_BUFFER_SIZE_MAX=8192
CONFIG_USE_AUDIO_PROCESSOR=y
# CONFIG_USE_DEVICE_AEC is not set
# CONFIG_USE_SERVER_AEC is not set
CONFIG_USE_WECHAT_MESSAGE_STYLE=n
CONFIG_USE_ESP_BLUFI_WIFI_PROVISIONING=y
CONFIG_BT_ENABLED=y
CONFIG_BT_BLUEDROID_ENABLED=y
CONFIG_BT_BLE_42_FEATURES_SUPPORTED=y
# CONFIG_BT_BLE_50_FEATURES_SUPPORTED is not set
CONFIG_BT_BLE_BLUFI_ENABLE=y
CONFIG_MBEDTLS_DHM_C=y
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions/v2/16m_atk_guard.csv"
CONFIG_LWIP_DNS_SUPPORT_MDNS_QUERIES=y
CONFIG_MDNS_MAX_SERVICES=10
CONFIG_ESP_WS_CLIENT_ENABLE_DYNAMIC_BUFFER=y
CONFIG_ESP_WS_CLIENT_SEPARATE_TX_LOCK=y
CONFIG_MBEDTLS_SSL_DTLS_SRTP=y
CONFIG_MBEDTLS_SSL_PROTO_DTLS=y
# ATK voice/control audio and bundled Ogg prompts are Opus end-to-end. Keep the
# managed esp_audio_codec registry limited to the codecs this image can use.
# CONFIG_AUDIO_DECODER_AAC_SUPPORT is not set
# CONFIG_AUDIO_DECODER_MP3_SUPPORT is not set
# CONFIG_AUDIO_DECODER_G711_SUPPORT is not set
# CONFIG_AUDIO_DECODER_AMRNB_SUPPORT is not set
# CONFIG_AUDIO_DECODER_AMRWB_SUPPORT is not set
# CONFIG_AUDIO_DECODER_FLAC_SUPPORT is not set
CONFIG_AUDIO_DECODER_OPUS_SUPPORT=y
# CONFIG_AUDIO_DECODER_VORBIS_SUPPORT is not set
# CONFIG_AUDIO_DECODER_ADPCM_SUPPORT is not set
# CONFIG_AUDIO_DECODER_ALAC_SUPPORT is not set
# CONFIG_AUDIO_DECODER_PCM_SUPPORT is not set
# CONFIG_AUDIO_DECODER_SBC_SUPPORT is not set
# CONFIG_AUDIO_DECODER_LC3_SUPPORT is not set
# CONFIG_AUDIO_SIMPLE_DEC_WAV_SUPPORT is not set
# CONFIG_AUDIO_SIMPLE_DEC_M4A_SUPPORT is not set
# CONFIG_AUDIO_SIMPLE_DEC_TS_SUPPORT is not set
# CONFIG_AUDIO_ENCODER_AAC_SUPPORT is not set
# CONFIG_AUDIO_ENCODER_G711_SUPPORT is not set
# CONFIG_AUDIO_ENCODER_AMRNB_SUPPORT is not set
# CONFIG_AUDIO_ENCODER_AMRWB_SUPPORT is not set
CONFIG_AUDIO_ENCODER_OPUS_SUPPORT=y
# CONFIG_AUDIO_ENCODER_ADPCM_SUPPORT is not set
# CONFIG_AUDIO_ENCODER_ALAC_SUPPORT is not set
# CONFIG_AUDIO_ENCODER_PCM_SUPPORT is not set
# CONFIG_AUDIO_ENCODER_SBC_SUPPORT is not set
# CONFIG_AUDIO_ENCODER_LC3_SUPPORT is not set
EOF
}

set_sdkconfig_value() {
  local key="$1"
  local value="$2"
  local file="${PROJECT_ROOT}/${SDKCONFIG_FILE}"
  [[ -f "${file}" ]] || return 0

  local rendered="${key}=${value}"
  if [[ "${value}" == "n" ]]; then
    rendered="# ${key} is not set"
  fi

  local tmp="${file}.tmp.$$"
  if grep -q "^${key}=" "${file}"; then
    sed "s|^${key}=.*|${rendered}|" "${file}" >"${tmp}"
  elif grep -q "^# ${key} is not set$" "${file}"; then
    sed "s|^# ${key} is not set$|${rendered}|" "${file}" >"${tmp}"
  else
    cp "${file}" "${tmp}"
    printf '%s\n' "${rendered}" >>"${tmp}"
  fi
  mv "${tmp}" "${file}"
}

sync_existing_sdkconfig() {
  set_sdkconfig_value CONFIG_PARTITION_TABLE_CUSTOM_FILENAME '"partitions/v2/16m_atk_guard.csv"'
  set_sdkconfig_value CONFIG_PARTITION_TABLE_FILENAME '"partitions/v2/16m_atk_guard.csv"'
  set_sdkconfig_value CONFIG_CAMERA_OV2640 n
  set_sdkconfig_value CONFIG_CAMERA_OV5640 y
  set_sdkconfig_value CONFIG_CAMERA_OV5640_AUTO_DETECT_DVP_INTERFACE_SENSOR y
  set_sdkconfig_value CONFIG_CAMERA_OV5640_DVP_YUV422_800X600_10FPS y
  set_sdkconfig_value CONFIG_CAMERA_OV5640_DVP_IF_FORMAT_INDEX_DEFAULT 0
  set_sdkconfig_value CONFIG_CAMERA_DMA_BUFFER_SIZE_MAX 8192
  set_sdkconfig_value CONFIG_EIDOLON_OWNER_FACE_PROFILE y
  set_sdkconfig_value CONFIG_EIDOLON_OWNER_PERSON_PRESENCE y
  set_sdkconfig_value CONFIG_EIDOLON_AMBIENT_PRESENCE_OWNER_AUTH y
  set_sdkconfig_value CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL 256
  # Interaction mode = half_duplex (no AEC on this board): enforce on an
  # existing sdkconfig too, else a stale PTT=y from the 2-mode era survives a
  # re-run (ESP-IDF does not re-apply overlay defaults to an existing config).
  set_sdkconfig_value CONFIG_EIDOLON_INTERACTION_MODE_PTT n
  set_sdkconfig_value CONFIG_EIDOLON_INTERACTION_MODE_HALF_DUPLEX y
  set_sdkconfig_value CONFIG_HUMAN_FACE_DETECT_MODEL_IN_FLASH_PARTITION y
  set_sdkconfig_value CONFIG_HUMAN_FACE_DETECT_MODEL_IN_FLASH_RODATA n
  set_sdkconfig_value CONFIG_HUMAN_FACE_FEAT_MODEL_IN_FLASH_PARTITION y
  set_sdkconfig_value CONFIG_HUMAN_FACE_FEAT_MODEL_IN_FLASH_RODATA n
  set_sdkconfig_value CONFIG_WAKE_WORD_DISABLED y
  set_sdkconfig_value CONFIG_USE_ESP_WAKE_WORD n
  set_sdkconfig_value CONFIG_USE_AFE_WAKE_WORD n
  set_sdkconfig_value CONFIG_USE_CUSTOM_WAKE_WORD n
  set_sdkconfig_value CONFIG_SEND_WAKE_WORD_DATA n
  set_sdkconfig_value CONFIG_SR_WN_WN9_NIHAOXIAOZHI_TTS n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_AAC_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_MP3_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_G711_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_AMRNB_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_AMRWB_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_FLAC_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_OPUS_SUPPORT y
  set_sdkconfig_value CONFIG_AUDIO_DECODER_VORBIS_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_ADPCM_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_ALAC_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_PCM_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_SBC_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_DECODER_LC3_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_SIMPLE_DEC_WAV_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_SIMPLE_DEC_M4A_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_SIMPLE_DEC_TS_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_ENCODER_AAC_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_ENCODER_G711_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_ENCODER_AMRNB_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_ENCODER_AMRWB_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_ENCODER_OPUS_SUPPORT y
  set_sdkconfig_value CONFIG_AUDIO_ENCODER_ADPCM_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_ENCODER_ALAC_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_ENCODER_PCM_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_ENCODER_SBC_SUPPORT n
  set_sdkconfig_value CONFIG_AUDIO_ENCODER_LC3_SUPPORT n
}

idf_args() {
  local defaults=(
    "${PROJECT_ROOT}/sdkconfig.defaults"
    "${PROJECT_ROOT}/sdkconfig.defaults.${BOARD_TARGET}"
    "${PROJECT_ROOT}/${SDKCONFIG_OVERLAY}"
  )
  local joined=""
  local file
  for file in "${defaults[@]}"; do
    [[ -f "${file}" ]] || continue
    [[ -n "${joined}" ]] && joined+=";"
    joined+="${file}"
  done

  printf '%s\n' \
    -B "${PROJECT_ROOT}/${BUILD_DIR}" \
    -DIDF_TARGET="${BOARD_TARGET}" \
    -DSDKCONFIG="${PROJECT_ROOT}/${SDKCONFIG_FILE}" \
    -DSDKCONFIG_DEFAULTS="${joined}" \
    -DBOARD_NAME="${BOARD_NAME}" \
    -DBOARD_TYPE="${BOARD_PATH}"
}

run_idf() {
  require_idf
  write_overlay
  sync_existing_sdkconfig
  local -a base_args=()
  while IFS= read -r arg; do
    base_args+=("${arg}")
  done < <(idf_args)
  (cd "${PROJECT_ROOT}" && idf.py "${base_args[@]}" "$@")
}

usage() {
  cat <<EOF
Usage: $0 <command>

Commands:
  build       Build ATK-DNESP32S3 Eidolon firmware
  flash       Flash ATK-DNESP32S3 Eidolon firmware (auto-verifies the build stamp)
  monitor     Open idf.py monitor
  verify      Read the boot build stamp over serial and diff vs the last build
  clean       Remove ${BUILD_DIR}
  list-ports  Print detected serial ports

Environment:
  EIDOLON_PORT=/dev/cu.usbmodemXXXX
  EIDOLON_LIVEKIT_SDK=0.3.7   Pin the LiveKit SDK version (forces clean re-resolve)
EOF
}

cmd="${1:-build}"
case "${cmd}" in
  build)
    eidolon_prepare_build "${PROJECT_ROOT}"
    run_idf build
    ;;
  flash)
    PORT="$(detect_port)"
    info "Using serial port: ${PORT}"
    eidolon_prepare_build "${PROJECT_ROOT}"
    run_idf -p "${PORT}" flash
    eidolon_verify_flashed "${PROJECT_ROOT}" "${PORT}"
    ;;
  monitor)
    PORT="$(detect_port)"
    info "Using serial port: ${PORT}"
    run_idf -p "${PORT}" monitor
    ;;
  clean)
    rm -rf "${PROJECT_ROOT}/${BUILD_DIR}"
    ;;
  list-ports)
    list_ports
    ;;
  verify)
    PORT="$(detect_port)"
    eidolon_verify_flashed "${PROJECT_ROOT}" "${PORT}"
    ;;
  help|-h|--help)
    usage
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
