#!/usr/bin/env bash
# Eidolon dev toolkit - Espressif ESP32-S31-Korvo-1
#
# Usage:
#   ./scripts/eidolon/eidolon-korvo-1.sh build
#   ./scripts/eidolon/eidolon-korvo-1.sh flash
#   ./scripts/eidolon/eidolon-korvo-1.sh monitor
#
# Environment:
#   EIDOLON_PORT         Serial port, e.g. /dev/cu.usbserial-110
#   EIDOLON_IDF_VERSION  Override the ESP-IDF version this board requires
#   EIDOLON_IDF_PATH / EIDOLON_IDF_EXPORT   Where an ESP-IDF lives
#   EIDOLON_PRIVATE_SDKCONFIG_OVERLAY Absolute path to a private setup-secret
#                        overlay, outside the repository, mode 0600, holding
#                        exactly CONFIG_EIDOLON_ADMISSION_SETUP_SECRET_HEX.
#                        Without it the board builds and flashes but cannot be
#                        admitted by a Hub.

set -euo pipefail

readonly BOARD_PATH="korvo-1"
readonly BOARD_NAME="korvo-1"
readonly BOARD_TARGET="esp32s31"
# esp32s31 exists only from ESP-IDF 6.1; release/v6.0 has no components/soc entry
# for it. Declared here so eidolon-common.sh resolves and verifies that exact
# toolchain instead of whatever is newest on the machine.
readonly BOARD_IDF_VERSION="6.1"
readonly PUBLIC_BUILD_DIR="build/eidolon/korvo-1"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
BUILD_DIR="${PROJECT_ROOT}/${PUBLIC_BUILD_DIR}"
SDKCONFIG_FILE="${BUILD_DIR}/sdkconfig.korvo-1"
SDKCONFIG_OVERLAY="${BUILD_DIR}/sdkconfig.overlay.korvo-1"
# Set by eidolon_configure_private_sdkconfig_overlay when the caller supplies a
# setup secret; empty means an ordinary public build.
PRIVATE_SDKCONFIG_OVERLAY=""
PORT="${EIDOLON_PORT:-}"

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/eidolon-common.sh"

die()  { echo "error: $*" >&2; exit 1; }
info() { echo ">> $*"; }

idf_ready()      { command -v idf.py >/dev/null 2>&1; }
ensure_idf_env() { eidolon_idf_ensure "${BOARD_IDF_VERSION}"; }
require_idf()    { eidolon_require_idf "${BOARD_IDF_VERSION}"; }

list_ports() {
  local -a patterns=(
    /dev/cu.usbserial*
    /dev/cu.usbmodem*
    /dev/cu.wchusbserial*
    /dev/cu.SLAB_USBtoUART*
    /dev/ttyUSB*
    /dev/ttyACM*
  )
  local p
  for p in "${patterns[@]}"; do
    [[ -e "${p}" ]] && echo "${p}"
  done
}

# Refuse to write to anything that is not an ESP32-S31.
#
# More than one Espressif board is normally attached to this desk, and the other
# one is an ESP32-S3 carrying firmware other people are using. Port names are not
# stable and EIDOLON_PORT can be set to the wrong one by hand, so the guarantee
# has to come from the chip answering for itself, not from a convention about
# which /dev entry belongs to which board.
verify_target_chip() {
  local port="$1" detected
  require_idf
  detected="$(esptool.py --port "${port}" --before default_reset --connect-attempts 2 chip_id 2>&1 |
              sed -n 's/^Detecting chip type\.\.\. //p;s/^Chip type: *\([^ ]*\).*/\1/p' | head -1)"
  if [[ -z "${detected}" ]]; then
    die "could not identify the chip on ${port}; refusing to flash blind"
  fi
  # ${var,,} is bash 4; macOS ships bash 3.2, so lowercase with tr instead.
  local normalized
  normalized="$(printf '%s' "${detected//-/}" | tr '[:upper:]' '[:lower:]')"
  if [[ "${normalized}" != "esp32s31" ]]; then
    die "${port} reports '${detected}', not ESP32-S31. Refusing to write — that is another board."
  fi
  info "Confirmed ESP32-S31 on ${port}"
}

detect_port() {
  if [[ -n "${PORT}" ]]; then
    echo "${PORT}"
    return 0
  fi
  local -a ports=()
  while IFS= read -r line; do
    [[ -n "${line}" ]] && ports+=("${line}")
  done < <(list_ports | sort -u)

  if ((${#ports[@]} == 0)); then
    die "No USB serial port found. Set EIDOLON_PORT=/dev/cu.xxx"
  fi
  if ((${#ports[@]} > 1)); then
    printf 'Multiple serial ports found; set EIDOLON_PORT explicitly:\n' >&2
    printf '  %s\n' "${ports[@]}" >&2
    exit 1
  fi
  echo "${ports[0]}"
}

write_overlay() {
  mkdir -p "${BUILD_DIR}"
  cat >"${SDKCONFIG_OVERLAY}" <<EOF
# Generated by scripts/eidolon/eidolon-korvo-1.sh
CONFIG_BOARD_TYPE_KORVO_1=y
CONFIG_EIDOLON_HUB_MODE=y
CONFIG_USE_AUDIO_PROCESSOR=y
CONFIG_USE_DEVICE_AEC=y
CONFIG_USE_SERVER_AEC=n
CONFIG_EIDOLON_DEVICE_AEC_AFE_MODE_LOW_COST=y
CONFIG_EIDOLON_AUTO_JOIN_ON_ACTIVATION=n
CONFIG_EIDOLON_DEV_DISABLE_AUTO_SHUTDOWN=y
# CONFIG_EIDOLON_INTERACTION_MODE_PTT is not set
# CONFIG_EIDOLON_INTERACTION_MODE_HALF_DUPLEX is not set
CONFIG_EIDOLON_FULL_DUPLEX_IDLE_FALLBACK_MS=75000
CONFIG_USE_DEFAULT_MESSAGE_STYLE=y
# CONFIG_USE_EMOTE_MESSAGE_STYLE is not set
# CONFIG_USE_WECHAT_MESSAGE_STYLE is not set
CONFIG_FLASH_DEFAULT_ASSETS=y
# CONFIG_FLASH_EXPRESSION_ASSETS is not set
# CONFIG_EIDOLON_WAKE_WORD_ENABLE is not set
CONFIG_WAKE_WORD_DISABLED=y
# CONFIG_USE_ESP_WAKE_WORD is not set
# CONFIG_USE_AFE_WAKE_WORD is not set
# CONFIG_USE_CUSTOM_WAKE_WORD is not set
CONFIG_EIDOLON_LIVEKIT_SPEAKER_VOLUME=70
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions/v2/16m_eidolon.csv"
CONFIG_LWIP_DNS_SUPPORT_MDNS_QUERIES=y
CONFIG_MDNS_MAX_SERVICES=10
CONFIG_ESP_WS_CLIENT_ENABLE_DYNAMIC_BUFFER=y
CONFIG_ESP_WS_CLIENT_SEPARATE_TX_LOCK=y
CONFIG_MBEDTLS_SSL_DTLS_SRTP=y
CONFIG_MBEDTLS_SSL_PROTO_DTLS=y
EOF
}

idf_args() {
  local defaults=(
    "${PROJECT_ROOT}/sdkconfig.defaults"
    "${PROJECT_ROOT}/sdkconfig.defaults.${BOARD_TARGET}"
    "${SDKCONFIG_OVERLAY}"
  )
  # Last, so the private setup secret wins over any public default.
  if [[ -n "${PRIVATE_SDKCONFIG_OVERLAY}" ]]; then
    defaults+=("${PRIVATE_SDKCONFIG_OVERLAY}")
  fi
  local joined="" file
  for file in "${defaults[@]}"; do
    [[ -f "${file}" ]] || continue
    [[ -n "${joined}" ]] && joined+=";"
    joined+="${file}"
  done

  printf '%s\n' \
    -B "${BUILD_DIR}" \
    -DIDF_TARGET="${BOARD_TARGET}" \
    -DSDKCONFIG="${SDKCONFIG_FILE}" \
    -DSDKCONFIG_DEFAULTS="${joined}" \
    -DBOARD_NAME="${BOARD_NAME}" \
    -DBOARD_TYPE="${BOARD_PATH}"
}

run_idf() {
  require_idf
  write_overlay
  if [[ -n "${PRIVATE_SDKCONFIG_OVERLAY}" ]]; then
    # Never let a previous private build pin a stale setup secret; the validated
    # overlay stays the only source.
    rm -f "${SDKCONFIG_FILE}"
  fi
  local -a base_args=()
  while IFS= read -r arg; do base_args+=("${arg}"); done < <(idf_args)
  (cd "${PROJECT_ROOT}" && idf.py "${base_args[@]}" "$@")
}

usage() {
  cat <<EOF
Usage: $0 <command>

Commands:
  build       Build ESP32-S31-Korvo-1 Eidolon firmware (ESP-IDF v${BOARD_IDF_VERSION})
  flash       Flash it — verifies the chip is an ESP32-S31 before writing
  monitor     Open idf.py monitor
  verify      Read the boot build stamp over serial and diff vs the last build
  clean       Remove ${BUILD_DIR}
  list-ports  Print detected serial ports

Environment:
  EIDOLON_PORT=/dev/cu.usbserial-XXX
  EIDOLON_IDF_VERSION=${BOARD_IDF_VERSION}
EOF
}

if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
  return 0
fi

eidolon_configure_private_sdkconfig_overlay "korvo-1"

cmd="${1:-build}"
case "${cmd}" in
  build)
    eidolon_prepare_build "${PROJECT_ROOT}" "${BOARD_IDF_VERSION}"
    run_idf build
    ;;
  flash)
    PORT="$(detect_port)"
    info "Using serial port: ${PORT}"
    verify_target_chip "${PORT}"
    eidolon_prepare_build "${PROJECT_ROOT}" "${BOARD_IDF_VERSION}"
    run_idf -p "${PORT}" flash
    eidolon_verify_flashed "${PROJECT_ROOT}" "${PORT}"
    ;;
  monitor)
    PORT="$(detect_port)"
    info "Using serial port: ${PORT}"
    run_idf -p "${PORT}" monitor
    ;;
  verify)
    PORT="$(detect_port)"
    eidolon_verify_flashed "${PROJECT_ROOT}" "${PORT}"
    ;;
  clean)      rm -rf "${BUILD_DIR}" ;;
  list-ports) list_ports ;;
  -h|--help|help) usage ;;
  *) usage >&2; exit 2 ;;
esac
