#!/usr/bin/env bash
# Eidolon dev toolkit - Espressif ESP-BOX-3
#
# Usage:
#   ./scripts/eidolon/eidolon-esp-box-3.sh build
#   ./scripts/eidolon/eidolon-esp-box-3.sh flash
#   ./scripts/eidolon/eidolon-esp-box-3.sh monitor
#
# Environment:
#   EIDOLON_PORT                       Serial port, for example /dev/cu.usbmodem1101
#   EIDOLON_IDF_EXPORT                 Full path to ESP-IDF export.sh
#   EIDOLON_IDF_PATH                   ESP-IDF root directory
#   EIDOLON_OWNER_PRESENCE_VOICE_WAKE Enable owner-confirmed voice join: y/n (default n)
#   IDF_PATH                           ESP-IDF root directory

set -euo pipefail

readonly BOARD_PATH="esp-box-3"
readonly BOARD_NAME="esp-box-3"
readonly BOARD_TARGET="esp32s3"
readonly BUILD_DIR="build/eidolon/esp-box-3"
readonly SDKCONFIG_FILE="${BUILD_DIR}/sdkconfig.esp-box-3"
readonly SDKCONFIG_OVERLAY="${BUILD_DIR}/sdkconfig.overlay.esp-box-3"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PORT="${EIDOLON_PORT:-}"
OWNER_PRESENCE_VOICE_WAKE="${EIDOLON_OWNER_PRESENCE_VOICE_WAKE:-n}"

if [[ "${OWNER_PRESENCE_VOICE_WAKE}" != "y" &&
      "${OWNER_PRESENCE_VOICE_WAKE}" != "n" ]]; then
  echo "error: EIDOLON_OWNER_PRESENCE_VOICE_WAKE must be y or n" >&2
  exit 2
fi

# Shared helper: SDK version pin + forced re-resolution, build fingerprint,
# post-flash serial verification. See scripts/eidolon/eidolon-common.sh.
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/eidolon-common.sh"

die() {
  echo "error: $*" >&2
  exit 1
}

info() {
  echo ">> $*"
}

idf_ready() {
  command -v idf.py >/dev/null 2>&1
}

idf_tools_ready() {
  idf_ready && command -v ninja >/dev/null 2>&1 && [[ -n "${IDF_PYTHON_ENV_PATH:-}" ]]
}

idf_export_candidates() {
  [[ -n "${EIDOLON_IDF_EXPORT:-}" ]] && echo "${EIDOLON_IDF_EXPORT}"

  local cfg="${SCRIPT_DIR}/idf.path"
  if [[ -f "${cfg}" ]]; then
    local line
    while IFS= read -r line || [[ -n "${line}" ]]; do
      line="${line%%#*}"
      line="${line#"${line%%[![:space:]]*}"}"
      line="${line%"${line##*[![:space:]]}"}"
      [[ -n "${line}" ]] && echo "${line%/}/export.sh"
    done <"${cfg}"
  fi

  [[ -n "${EIDOLON_IDF_PATH:-}" ]] && echo "${EIDOLON_IDF_PATH%/}/export.sh"
  [[ -n "${IDF_PATH:-}" ]] && echo "${IDF_PATH%/}/export.sh"

  local home="${HOME:-}"
  if [[ -n "${home}" ]]; then
    shopt -s nullglob
    local d
    for d in "${home}"/.espressif/v*/esp-idf/export.sh; do
      echo "${d}"
    done | sort -t'/' -k6 -V -r
    shopt -u nullglob
    echo "${home}/esp/esp-idf/export.sh"
    echo "${home}/esp-idf/export.sh"
  fi
}

ensure_idf_env() {
  if idf_tools_ready; then
    return 0
  fi

  local export_sh
  while IFS= read -r export_sh; do
    [[ -f "${export_sh}" ]] || continue
    info "Loading ESP-IDF: ${export_sh}"
    # shellcheck source=/dev/null
    source "${export_sh}"
    idf_tools_ready && return 0
  done < <(idf_export_candidates | awk '!seen[$0]++')

  return 1
}

require_idf() {
  ensure_idf_env || die "ESP-IDF tools not ready. Set EIDOLON_IDF_PATH/EIDOLON_IDF_EXPORT or source export.sh first."
}

list_ports() {
  local -a patterns=(
    /dev/cu.usbmodem*
    /dev/cu.wchusbserial*
    /dev/cu.SLAB_USBtoUART*
    /dev/cu.usbserial*
    /dev/ttyUSB*
    /dev/ttyACM*
  )
  local p
  for p in "${patterns[@]}"; do
    [[ -e "${p}" ]] && echo "${p}"
  done
}

detect_port() {
  if [[ -n "${PORT}" ]]; then
    echo "${PORT}"
    return 0
  fi

  local -a ports=()
  while IFS= read -r line; do
    [[ -n "${line}" ]] && ports+=("${line}")
  done < <(list_ports | sort -u)

  if ((${#ports[@]} == 0)); then
    die "No USB serial port found. Set EIDOLON_PORT=/dev/cu.xxx"
  fi
  if ((${#ports[@]} > 1)); then
    printf 'Multiple serial ports found; set EIDOLON_PORT explicitly:\n' >&2
    printf '  %s\n' "${ports[@]}" >&2
    exit 1
  fi
  echo "${ports[0]}"
}

write_overlay() {
  mkdir -p "${PROJECT_ROOT}/${BUILD_DIR}"
  cat >"${PROJECT_ROOT}/${SDKCONFIG_OVERLAY}" <<EOF
# Generated by scripts/eidolon/eidolon-esp-box-3.sh
CONFIG_BOARD_TYPE_ESP_BOX_3=y
CONFIG_USE_AUDIO_PROCESSOR=y
CONFIG_USE_DEVICE_AEC=y
CONFIG_USE_SERVER_AEC=n
CONFIG_EIDOLON_DEVICE_AEC_AFE_MODE_LOW_COST=y
# CONFIG_EIDOLON_DEVICE_AEC_AFE_MODE_HIGH_PERF is not set
CONFIG_EIDOLON_HUB_MODE=y
CONFIG_EIDOLON_AUTO_JOIN_ON_ACTIVATION=n
CONFIG_EIDOLON_DEV_DISABLE_AUTO_SHUTDOWN=y
CONFIG_EIDOLON_RADAR_PRESENCE_PUBLISH=y
CONFIG_EIDOLON_OWNER_PRESENCE_VOICE_WAKE=${OWNER_PRESENCE_VOICE_WAKE}
# CONFIG_EIDOLON_INTERACTION_MODE_PTT is not set
# CONFIG_EIDOLON_INTERACTION_MODE_HALF_DUPLEX is not set
CONFIG_EIDOLON_FULL_DUPLEX_IDLE_FALLBACK_MS=75000
CONFIG_USE_EMOTE_MESSAGE_STYLE=y
# CONFIG_USE_DEFAULT_MESSAGE_STYLE is not set
# CONFIG_USE_WECHAT_MESSAGE_STYLE is not set
# CONFIG_FLASH_DEFAULT_ASSETS is not set
CONFIG_FLASH_EXPRESSION_ASSETS=y
# CONFIG_EIDOLON_WAKE_WORD_ENABLE is not set
CONFIG_WAKE_WORD_DISABLED=y
# CONFIG_USE_ESP_WAKE_WORD is not set
# CONFIG_USE_AFE_WAKE_WORD is not set
# CONFIG_USE_CUSTOM_WAKE_WORD is not set
CONFIG_EIDOLON_LIVEKIT_SPEAKER_VOLUME=80
CONFIG_MMAP_FILE_NAME_LENGTH=32
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions/v2/16m_eidolon_box3.csv"
CONFIG_LWIP_DNS_SUPPORT_MDNS_QUERIES=y
CONFIG_MDNS_MAX_SERVICES=10
CONFIG_ESP_WS_CLIENT_ENABLE_DYNAMIC_BUFFER=y
CONFIG_ESP_WS_CLIENT_SEPARATE_TX_LOCK=y
CONFIG_MBEDTLS_SSL_DTLS_SRTP=y
CONFIG_MBEDTLS_SSL_PROTO_DTLS=y
EOF
}

set_sdkconfig_bool() {
  local key="$1"
  local value="$2"
  local sdkconfig="${PROJECT_ROOT}/${SDKCONFIG_FILE}"
  local tmp="${sdkconfig}.tmp"

  mkdir -p "$(dirname "${sdkconfig}")"
  touch "${sdkconfig}"
  awk -v key="${key}" '
    $0 == "CONFIG_" key "=y" { next }
    $0 == "CONFIG_" key "=n" { next }
    $0 == "# CONFIG_" key " is not set" { next }
    { print }
  ' "${sdkconfig}" >"${tmp}"

  if [[ "${value}" == "y" ]]; then
    printf 'CONFIG_%s=y\n' "${key}" >>"${tmp}"
  else
    printf '# CONFIG_%s is not set\n' "${key}" >>"${tmp}"
  fi
  mv "${tmp}" "${sdkconfig}"
}

set_sdkconfig_value() {
  local key="$1"
  local value="$2"
  local sdkconfig="${PROJECT_ROOT}/${SDKCONFIG_FILE}"
  local tmp="${sdkconfig}.tmp"

  mkdir -p "$(dirname "${sdkconfig}")"
  touch "${sdkconfig}"
  awk -v key="${key}" '
    index($0, "CONFIG_" key "=") == 1 { next }
    $0 == "# CONFIG_" key " is not set" { next }
    { print }
  ' "${sdkconfig}" >"${tmp}"
  printf 'CONFIG_%s=%s\n' "${key}" "${value}" >>"${tmp}"
  mv "${tmp}" "${sdkconfig}"
}

ensure_box3_sdkconfig() {
  set_sdkconfig_bool BOARD_TYPE_ESP_BOX_3 y
  set_sdkconfig_bool EIDOLON_HUB_MODE y
  set_sdkconfig_bool EIDOLON_AUTO_JOIN_ON_ACTIVATION n
  set_sdkconfig_bool EIDOLON_DEV_DISABLE_AUTO_SHUTDOWN y
  set_sdkconfig_bool EIDOLON_RADAR_PRESENCE_PUBLISH y
  set_sdkconfig_bool EIDOLON_OWNER_PRESENCE_VOICE_WAKE "${OWNER_PRESENCE_VOICE_WAKE}"
  set_sdkconfig_bool EIDOLON_INTERACTION_MODE_PTT n
  set_sdkconfig_bool USE_DEVICE_AEC y
  set_sdkconfig_bool EIDOLON_INTERACTION_MODE_HALF_DUPLEX n

  set_sdkconfig_bool USE_DEFAULT_MESSAGE_STYLE n
  set_sdkconfig_bool USE_WECHAT_MESSAGE_STYLE n
  set_sdkconfig_bool USE_EMOTE_MESSAGE_STYLE y
  set_sdkconfig_bool FLASH_NONE_ASSETS n
  set_sdkconfig_bool FLASH_DEFAULT_ASSETS n
  set_sdkconfig_bool FLASH_CUSTOM_ASSETS n
  set_sdkconfig_bool FLASH_EXPRESSION_ASSETS y

  set_sdkconfig_bool EIDOLON_WAKE_WORD_ENABLE n
  set_sdkconfig_bool WAKE_WORD_DISABLED y
  set_sdkconfig_bool USE_ESP_WAKE_WORD n
  set_sdkconfig_bool USE_AFE_WAKE_WORD n
  set_sdkconfig_bool USE_CUSTOM_WAKE_WORD n

  set_sdkconfig_value EIDOLON_LIVEKIT_SPEAKER_VOLUME 80
  set_sdkconfig_value EIDOLON_FULL_DUPLEX_IDLE_FALLBACK_MS 75000
  set_sdkconfig_value MMAP_FILE_NAME_LENGTH 32
  set_sdkconfig_value PARTITION_TABLE_CUSTOM_FILENAME '"partitions/v2/16m_eidolon_box3.csv"'
}

idf_args() {
  local defaults=(
    "${PROJECT_ROOT}/sdkconfig.defaults"
    "${PROJECT_ROOT}/sdkconfig.defaults.${BOARD_TARGET}"
    "${PROJECT_ROOT}/${SDKCONFIG_OVERLAY}"
  )
  local joined=""
  local file
  for file in "${defaults[@]}"; do
    [[ -f "${file}" ]] || continue
    [[ -n "${joined}" ]] && joined+=";"
    joined+="${file}"
  done

  printf '%s\n' \
    -B "${PROJECT_ROOT}/${BUILD_DIR}" \
    -DIDF_TARGET="${BOARD_TARGET}" \
    -DSDKCONFIG="${PROJECT_ROOT}/${SDKCONFIG_FILE}" \
    -DSDKCONFIG_DEFAULTS="${joined}" \
    -DBOARD_NAME="${BOARD_NAME}" \
    -DBOARD_TYPE="${BOARD_PATH}"
}

run_idf() {
  require_idf
  write_overlay
  ensure_box3_sdkconfig
  local -a base_args=()
  while IFS= read -r arg; do
    base_args+=("${arg}")
  done < <(idf_args)
  (cd "${PROJECT_ROOT}" && idf.py "${base_args[@]}" "$@")
}

usage() {
  cat <<EOF
Usage: $0 <command>

Commands:
  build       Build ESP-BOX-3 Eidolon firmware
  flash       Flash ESP-BOX-3 Eidolon firmware (auto-verifies the build stamp)
  monitor     Open idf.py monitor
  verify      Read the boot build stamp over serial and diff vs the last build
  clean       Remove ${BUILD_DIR}
  list-ports  Print detected serial ports

Environment:
  EIDOLON_PORT=/dev/cu.usbmodemXXXX
  EIDOLON_LIVEKIT_SDK=0.3.7   Pin the LiveKit SDK version (forces clean re-resolve)
  EIDOLON_OWNER_PRESENCE_VOICE_WAKE=y
                               Compile owner-confirmed automatic voice join
EOF
}

cmd="${1:-build}"
case "${cmd}" in
  build)
    eidolon_prepare_build "${PROJECT_ROOT}"
    run_idf build
    ;;
  flash)
    PORT="$(detect_port)"
    info "Using serial port: ${PORT}"
    eidolon_prepare_build "${PROJECT_ROOT}"
    run_idf -p "${PORT}" flash
    eidolon_verify_flashed "${PROJECT_ROOT}" "${PORT}"
    ;;
  monitor)
    PORT="$(detect_port)"
    info "Using serial port: ${PORT}"
    run_idf -p "${PORT}" monitor
    ;;
  clean)
    rm -rf "${PROJECT_ROOT}/${BUILD_DIR}"
    ;;
  list-ports)
    list_ports
    ;;
  verify)
    PORT="$(detect_port)"
    eidolon_verify_flashed "${PROJECT_ROOT}" "${PORT}"
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
