#!/usr/bin/env bash
# Eidolon dev toolkit - Espressif ESP-BOX-3
#
# Usage:
#   ./scripts/eidolon/eidolon-esp-box-3.sh build
#   ./scripts/eidolon/eidolon-esp-box-3.sh flash
#   ./scripts/eidolon/eidolon-esp-box-3.sh monitor
#
# Environment:
#   EIDOLON_PORT        Serial port, for example /dev/cu.usbmodem1101
#   EIDOLON_IDF_EXPORT Full path to ESP-IDF export.sh
#   EIDOLON_IDF_PATH   ESP-IDF root directory
#   IDF_PATH           ESP-IDF root directory

set -euo pipefail

readonly BOARD_PATH="esp-box-3"
readonly BOARD_NAME="esp-box-3"
readonly BOARD_TARGET="esp32s3"
readonly BUILD_DIR="build/eidolon/esp-box-3"
readonly SDKCONFIG_FILE="${BUILD_DIR}/sdkconfig.esp-box-3"
readonly SDKCONFIG_OVERLAY="${BUILD_DIR}/sdkconfig.overlay.esp-box-3"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PORT="${EIDOLON_PORT:-}"

die() {
  echo "error: $*" >&2
  exit 1
}

info() {
  echo ">> $*"
}

idf_ready() {
  command -v idf.py >/dev/null 2>&1
}

idf_tools_ready() {
  idf_ready && command -v ninja >/dev/null 2>&1 && [[ -n "${IDF_PYTHON_ENV_PATH:-}" ]]
}

idf_export_candidates() {
  [[ -n "${EIDOLON_IDF_EXPORT:-}" ]] && echo "${EIDOLON_IDF_EXPORT}"

  local cfg="${SCRIPT_DIR}/idf.path"
  if [[ -f "${cfg}" ]]; then
    local line
    while IFS= read -r line || [[ -n "${line}" ]]; do
      line="${line%%#*}"
      line="${line#"${line%%[![:space:]]*}"}"
      line="${line%"${line##*[![:space:]]}"}"
      [[ -n "${line}" ]] && echo "${line%/}/export.sh"
    done <"${cfg}"
  fi

  [[ -n "${EIDOLON_IDF_PATH:-}" ]] && echo "${EIDOLON_IDF_PATH%/}/export.sh"
  [[ -n "${IDF_PATH:-}" ]] && echo "${IDF_PATH%/}/export.sh"

  local home="${HOME:-}"
  if [[ -n "${home}" ]]; then
    shopt -s nullglob
    local d
    for d in "${home}"/.espressif/v*/esp-idf/export.sh; do
      echo "${d}"
    done | sort -t'/' -k6 -V -r
    shopt -u nullglob
    echo "${home}/esp/esp-idf/export.sh"
    echo "${home}/esp-idf/export.sh"
  fi
}

ensure_idf_env() {
  if idf_tools_ready; then
    return 0
  fi

  local export_sh
  while IFS= read -r export_sh; do
    [[ -f "${export_sh}" ]] || continue
    info "Loading ESP-IDF: ${export_sh}"
    # shellcheck source=/dev/null
    source "${export_sh}"
    idf_tools_ready && return 0
  done < <(idf_export_candidates | awk '!seen[$0]++')

  return 1
}

require_idf() {
  ensure_idf_env || die "ESP-IDF tools not ready. Set EIDOLON_IDF_PATH/EIDOLON_IDF_EXPORT or source export.sh first."
}

list_ports() {
  local -a patterns=(
    /dev/cu.usbmodem*
    /dev/cu.wchusbserial*
    /dev/cu.SLAB_USBtoUART*
    /dev/cu.usbserial*
    /dev/ttyUSB*
    /dev/ttyACM*
  )
  local p
  for p in "${patterns[@]}"; do
    [[ -e "${p}" ]] && echo "${p}"
  done
}

detect_port() {
  if [[ -n "${PORT}" ]]; then
    echo "${PORT}"
    return 0
  fi

  local -a ports=()
  while IFS= read -r line; do
    [[ -n "${line}" ]] && ports+=("${line}")
  done < <(list_ports | sort -u)

  if ((${#ports[@]} == 0)); then
    die "No USB serial port found. Set EIDOLON_PORT=/dev/cu.xxx"
  fi
  if ((${#ports[@]} > 1)); then
    printf 'Multiple serial ports found; set EIDOLON_PORT explicitly:\n' >&2
    printf '  %s\n' "${ports[@]}" >&2
    exit 1
  fi
  echo "${ports[0]}"
}

write_overlay() {
  mkdir -p "${PROJECT_ROOT}/${BUILD_DIR}"
  cat >"${PROJECT_ROOT}/${SDKCONFIG_OVERLAY}" <<EOF
# Generated by scripts/eidolon/eidolon-esp-box-3.sh
CONFIG_BOARD_TYPE_ESP_BOX_3=y
CONFIG_USE_AUDIO_PROCESSOR=y
CONFIG_USE_DEVICE_AEC=y
CONFIG_USE_SERVER_AEC=n
CONFIG_EIDOLON_DEVICE_AEC_AFE_MODE_LOW_COST=y
# CONFIG_EIDOLON_DEVICE_AEC_AFE_MODE_HIGH_PERF is not set
CONFIG_EIDOLON_HUB_MODE=y
CONFIG_EIDOLON_AUTO_JOIN_ON_ACTIVATION=n
CONFIG_EIDOLON_DEV_DISABLE_AUTO_SHUTDOWN=y
# CONFIG_EIDOLON_INTERACTION_MODE_PTT is not set
CONFIG_EIDOLON_LIVEKIT_SPEAKER_VOLUME=50
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions/v2/16m_eidolon_box3.csv"
CONFIG_LWIP_DNS_SUPPORT_MDNS_QUERIES=y
CONFIG_MDNS_MAX_SERVICES=10
CONFIG_ESP_WS_CLIENT_ENABLE_DYNAMIC_BUFFER=y
CONFIG_ESP_WS_CLIENT_SEPARATE_TX_LOCK=y
CONFIG_MBEDTLS_SSL_DTLS_SRTP=y
CONFIG_MBEDTLS_SSL_PROTO_DTLS=y
EOF
}

idf_args() {
  local defaults=(
    "${PROJECT_ROOT}/sdkconfig.defaults"
    "${PROJECT_ROOT}/sdkconfig.defaults.${BOARD_TARGET}"
    "${PROJECT_ROOT}/${SDKCONFIG_OVERLAY}"
  )
  local joined=""
  local file
  for file in "${defaults[@]}"; do
    [[ -f "${file}" ]] || continue
    [[ -n "${joined}" ]] && joined+=";"
    joined+="${file}"
  done

  printf '%s\n' \
    -B "${PROJECT_ROOT}/${BUILD_DIR}" \
    -DIDF_TARGET="${BOARD_TARGET}" \
    -DSDKCONFIG="${PROJECT_ROOT}/${SDKCONFIG_FILE}" \
    -DSDKCONFIG_DEFAULTS="${joined}" \
    -DBOARD_NAME="${BOARD_NAME}" \
    -DBOARD_TYPE="${BOARD_PATH}"
}

run_idf() {
  require_idf
  write_overlay
  local -a base_args=()
  while IFS= read -r arg; do
    base_args+=("${arg}")
  done < <(idf_args)
  (cd "${PROJECT_ROOT}" && idf.py "${base_args[@]}" "$@")
}

usage() {
  cat <<EOF
Usage: $0 <command>

Commands:
  build       Build ESP-BOX-3 Eidolon firmware
  flash       Flash ESP-BOX-3 Eidolon firmware
  monitor     Open idf.py monitor
  clean       Remove ${BUILD_DIR}
  list-ports  Print detected serial ports

Environment:
  EIDOLON_PORT=/dev/cu.usbmodemXXXX
EOF
}

cmd="${1:-build}"
case "${cmd}" in
  build)
    run_idf build
    ;;
  flash)
    PORT="$(detect_port)"
    info "Using serial port: ${PORT}"
    run_idf -p "${PORT}" flash
    ;;
  monitor)
    PORT="$(detect_port)"
    info "Using serial port: ${PORT}"
    run_idf -p "${PORT}" monitor
    ;;
  clean)
    rm -rf "${PROJECT_ROOT}/${BUILD_DIR}"
    ;;
  list-ports)
    list_ports
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
